[c++-analyzer] valgrind: minor changes

diff --git a/tools/c++-analyzer/valgrind b/tools/c++-analyzer/valgrind
--- a/tools/c++-analyzer/valgrind
+++ b/tools/c++-analyzer/valgrind
@@ -2,8 +2,8 @@
 
 cd "$(dirname "$0")"/../..
 
-TEMP=`getopt -o hqd: --long help -n "$0" -- "$@"`
-[ $? -ne 0 ] && exit 1
+TEMP=`getopt -o hxqd: --long help -n "$0" -- "$@"`
+(( $? != 0 )) && exit 1
 
 eval set -- "$TEMP"
 
@@ -12,6 +12,7 @@ q=show_full_error
 
 while true ; do
   case "$1" in
+    -x) set -x ; shift 1 ;;
     -d) d="$2/" ; shift 2 ;;
     -q) q=show_resume_error ; shift 1 ;;
     -h|--help) echo "$0 [-d binary-directory] [-q] [testnames...]" ; exit 0 ;;
@@ -29,14 +30,13 @@ show_resume_error ()
         --max-stackframe=234425648 \
         --track-fds=yes \
         "$f" 2>&1 >/dev/null`
-    error=`grep -E '^==[0-9]+== ERROR SUMMARY: [1-9]' -m1 <<< "$outvalgrind"`
-    [ $? = 0 ] && read a o <<<"$error" && echo "valgrind error: $f: $o"
-    leak=`grep -E '^==[0-9]+==    definitely lost: [1-9]' -m1 <<< "$outvalgrind"`
-    [ $? = 0 ] && read a o <<<"$leak" && echo "valgrind leak: $f: $o"
-    grep -E '^==[0-9]+== Open file descriptor ([3-9]:|[0-9][^:])' <<< "$outvalgrind" \
-    | while read a o ; do
+    error=`grep -E '^==[0-9]+== ERROR SUMMARY: [1-9]' -m1 <<< "$outvalgrind"` \
+    && read a o <<<"$error" && echo "valgrind error: $f: $o"
+    leak=`grep -E '^==[0-9]+==    definitely lost: [1-9]' -m1 <<< "$outvalgrind"` \
+    && read a o <<<"$leak" && echo "valgrind leak: $f: $o"
+    while read a o ; do
         echo "valgrind error: $f: $o"
-    done
+    done < <(grep -E '^==[0-9]+== Open file descriptor ([3-9]:|[0-9][^:])' <<< "$outvalgrind")
   done
 }
 
@@ -54,7 +54,7 @@ show_full_error ()
     error=`grep -E '^==[0-9]+== ERROR SUMMARY' -m1 <<< "$outvalgrind"`
     read p e s n other <<< "$error"
     grep -E '^==[0-9]+== +at 0x[A-F0-9]+: ' -q <<< "$outvalgrind"
-    if [ $? = 0 ] || [ $n != 0 ] ; then
+    if (( $? == 0 )) || (( $n != 0 )) ; then
         alloc=`grep -E '^==[0-9]+==   total heap usage:' -m1 <<< "$outvalgrind"`
         read p t h u n1 a n2 other <<< "$alloc"
         echo -n "$f"
@@ -77,7 +77,7 @@ show_full_error ()
   exec rm "$outfile"
 }
 
-if [ ! -z "$*" ] ; then
+if [[ ! -z "$*" ]] ; then
   read -a files <<< "$@"
   ls "${files[@]/#/$d}"
 else
